// File generated by the FlutterFire CLI, then hand-annotated.
//
// This is a PLACEHOLDER. Replace this file by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
// from the `frontend/` directory, selecting your Firebase project. That
// command will overwrite this file with real apiKey/appId/projectId values
// for each platform (web, android, ios, macos, windows).
//
// SECURITY NOTE: Firebase Web/Android/iOS "API keys" in this file are NOT
// secret — they identify your Firebase project to Google's servers, and
// access is enforced by Firestore/Storage security rules and App Check,
// not by hiding this file. It is safe to commit once populated. The truly
// sensitive secrets (Stripe keys, AI provider keys, social OAuth secrets)
// live only in functions/.env / Cloud Functions config, never here.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to generate real values.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMxYuJTJ0T7m2pWLVuv5fQqIrlG2FFGcI',
    appId: '1:771760533066:web:0cbb57f517ddc243c380b3',
    messagingSenderId: '771760533066',
    projectId: 'flacronsocialauto',
    authDomain: 'flacronsocialauto.firebaseapp.com',
    storageBucket: 'flacronsocialauto.firebasestorage.app',
    measurementId: 'G-1EGLTKSYQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiGfR4riO-7qZkYl3CsLU4mM3wwceJMxA',
    appId: '1:771760533066:android:33350a125eaada96c380b3',
    messagingSenderId: '771760533066',
    projectId: 'flacronsocialauto',
    storageBucket: 'flacronsocialauto.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5evB3-kqe85RDfaVSxf8s5-KbQsgCQRQ',
    appId: '1:771760533066:ios:a61e40526e8bf311c380b3',
    messagingSenderId: '771760533066',
    projectId: 'flacronsocialauto',
    storageBucket: 'flacronsocialauto.firebasestorage.app',
    iosClientId: '771760533066-ktnp5h98ems89nbqt9hjkro3g31j3ej8.apps.googleusercontent.com',
    iosBundleId: 'com.flacron.flacronAutoSocial',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'flacron-auto-social-dev',
    storageBucket: 'flacron-auto-social-dev.appspot.com',
    iosBundleId: 'com.flacron.autosocial',
  );
}
